queue_rules:
  - name: default
    conditions:
      - "check-success=CI completion"
    merge_method: rebase
    update_method: rebase
    allow_inplace_checks: true

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "linear-history"
      - "base=master"
      - "label!=work-in-progress"
    actions:
        queue:
            name: default
            update_method: rebase
            method: rebase

  - name: Remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
