#!/usr/bin/env python3
from backup import FileBackend, get_backend
import os
import click
import json


@click.command()
@click.argument("lightning-dir", type=click.Path(exists=True))
@click.argument("destination")
def init(lightning_dir, destination):
    backend = get_backend(destination)
    backend.version, backend.prev_version = 0, 0
    backend.offsets = [512, 0]
    backend.version_count = 0
    backend.write_metadata()

    lock_file = os.path.join(lightning_dir, "backup.lock")

    with open(lock_file, "w") as f:
        f.write(json.dumps({
            'backend_url': destination,
        }))

    # TODO Take a snapshot

    print("Initialized backup backend {destination}, you can now start c-lightning".format(
        destination=destination,
    ))


@click.group()
def cli():
    pass


cli.add_command(init)

if __name__ == "__main__":
    cli()
