# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/sendpage.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SendPage(object):
    def setupUi(self, SendPage):
        SendPage.setObjectName("SendPage")
        SendPage.resize(661, 333)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SendPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameTop = QtWidgets.QFrame(SendPage)
        self.frameTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTop.setObjectName("frameTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameTop)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frameTop)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.lineInvoice = QtWidgets.QLineEdit(self.frameTop)
        self.lineInvoice.setObjectName("lineInvoice")
        self.horizontalLayout_4.addWidget(self.lineInvoice)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frameTop)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.spinValue = QtWidgets.QSpinBox(self.frameTop)
        self.spinValue.setObjectName("spinValue")
        self.horizontalLayout_5.addWidget(self.spinValue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.buttonDecode = QtWidgets.QPushButton(self.frameTop)
        self.buttonDecode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buttonDecode.setObjectName("buttonDecode")
        self.horizontalLayout_11.addWidget(self.buttonDecode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.frameTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(SendPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.labelValue = QtWidgets.QLabel(SendPage)
        self.labelValue.setText("")
        self.labelValue.setObjectName("labelValue")
        self.horizontalLayout_7.addWidget(self.labelValue)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(SendPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.labelExpiry = QtWidgets.QLabel(SendPage)
        self.labelExpiry.setText("")
        self.labelExpiry.setObjectName("labelExpiry")
        self.horizontalLayout_9.addWidget(self.labelExpiry)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(SendPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.labelDescription = QtWidgets.QLabel(SendPage)
        self.labelDescription.setText("")
        self.labelDescription.setWordWrap(True)
        self.labelDescription.setObjectName("labelDescription")
        self.horizontalLayout_6.addWidget(self.labelDescription)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.label_6 = QtWidgets.QLabel(SendPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.labelPublicKey = QtWidgets.QLabel(SendPage)
        self.labelPublicKey.setText("")
        self.labelPublicKey.setWordWrap(True)
        self.labelPublicKey.setObjectName("labelPublicKey")
        self.horizontalLayout_8.addWidget(self.labelPublicKey)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.buttonPay = QtWidgets.QPushButton(SendPage)
        self.buttonPay.setMaximumSize(QtCore.QSize(200, 16777215))
        self.buttonPay.setObjectName("buttonPay")
        self.horizontalLayout_13.addWidget(self.buttonPay)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem6)
        self.labelPaymentResult = QtWidgets.QLabel(SendPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelPaymentResult.setFont(font)
        self.labelPaymentResult.setText("")
        self.labelPaymentResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPaymentResult.setObjectName("labelPaymentResult")
        self.verticalLayout_7.addWidget(self.labelPaymentResult)
        self.horizontalLayout_12.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)

        self.retranslateUi(SendPage)
        QtCore.QMetaObject.connectSlotsByName(SendPage)

    def retranslateUi(self, SendPage):
        _translate = QtCore.QCoreApplication.translate
        SendPage.setWindowTitle(_translate("SendPage", "Form"))
        self.label.setToolTip(_translate("SendPage", "In order to pay, you need to specify a bolt11 encoded invoice."))
        self.label.setText(_translate("SendPage", "Invoice :"))
        self.label_2.setToolTip(_translate("SendPage", "To set (in msat) only if not already set in the invoice"))
        self.label_2.setText(_translate("SendPage", "Value (optional) :"))
        self.buttonDecode.setToolTip(_translate("SendPage", "Decode the invoice in order to pay it afterwards."))
        self.buttonDecode.setText(_translate("SendPage", "Decode invoice"))
        self.label_8.setToolTip(_translate("SendPage", "The value requested by the invoice."))
        self.label_8.setText(_translate("SendPage", "Value :"))
        self.label_4.setToolTip(_translate("SendPage", "The invoice expiration."))
        self.label_4.setText(_translate("SendPage", "Expiry :"))
        self.label_7.setToolTip(_translate("SendPage", "The description set by the payee."))
        self.label_7.setText(_translate("SendPage", "Description :"))
        self.label_6.setToolTip(_translate("SendPage", "Public key of the payee node"))
        self.label_6.setText(_translate("SendPage", "Payee id :"))
        self.buttonPay.setText(_translate("SendPage", "Pay"))


