[tool.poetry]
name = "cln-backup"
version = "0.1.0"
description = "Keep your Core-Lightning node save by backing it up, in real-time (allows recovering without channel closures)."
authors = ["Christian Decker <decker@blockstream.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyln-client = "0.12.1"
click = "^8.0.4"
tqdm = "^4.62.3"
psutil = "5.9.4"
flask = "2.2.2"

[tool.poetry.group.dev.dependencies]
pyln-testing = "0.12.1"
flaky = "^3.7.0"
pytest-timeout = "^2.1.0"
pytest-xdist = "^3.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
