#! /usr/bin/make

check:
	@# E501 line too long (N > 79 characters)
	@# E731 do not assign a lambda expression, use a def
	@# W503: line break before binary operator
	@flake8 --ignore=E501,E731,W503 *.py
